### ISSUE TITLE
Doesn't work for me ( Europe Country ?)

### ISSUE THREAD

**Issue by profesionalleet1337** [mfr-fr/sms-sender#7]
I tried to use it, but didn't work for me. I tried to send to Europe country number, and its said that the messages was sent succesfully, but it doesn't received ? Is this working for anyone else or not ?

**Comment by mfr-fr** [comment]
hello have you tried? and did you try with a token or without? if not try with a token

**Comment by profesionalleet1337** [comment]
> hello have you tried? and did you try with a token or without? if not try with a token

Yes I tried. As I see textbelt doesn't offer a free API at the moment ? I need to purchase and paid, if I am correct ?
Before hald an year, there was an option, for free API , right ? 
I tried without API, and got this message, when checking the status : "{'success': True, 'status': 'FAILED'}"

**Comment by profesionalleet1337** [comment]
@mfr-fr any suggestions/ help ?

**Comment by mfr-fr** [comment]
hi if you check without token you have one free message per day, otherwise for everything related to the API I advise you to go directly to texblet because it is their API
